---
title       : Predicting Vehicle Fuel Economy
subtitle    : Developing Data Products Course Project
author      : Boukhris-Escandon
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Application Pitch

* The purpose of this presentation is to pitch an application that allows users to predict the fuel economy of their vehicle.
* The application was developed using Shiny in R and deployed on R Studio's Shiny server.
* This presentation was created using Slidify.

--- .class #id 

## Model Development

* A linear model was developed using the mtcars data set to predict miles per gallon based on number of cylinders, horsepower, and transmission type:

```{r, echo=TRUE}
lm(mpg ~ cyl + hp + am, data=mtcars)
```

##### The final equation therefore is:

mpg = 30.889 - 1.127*cyl - 0.03688*hp + 3.9043*am


--- .class #id 

## How to use the Application

* First the user selects the numeric value of the number of cylinders the vehicle has. The selection ranges from 0 to 12 with the pre-filled value of 4.
* Then the user fills in the numeric value of the approximate horsepower of their vehicle. The selection ranges from 70 to 700 in increments of 10. The pre-filled value is 170.
* The last selection the user makes is to use the radio buttons to select the type of transmission the vehicle has. The choices are automatic or manual.
* The last step is to press the "Calculate MPG!" button to begin the calculation. The result shows up of the right hand side of the application.


--- .class #id 

## Github and Shiny Server

* You can find the code written for this project at [https://github.com/boukhrisescandon/Data-Products-Course-Project](https://github.com/boukhrisescandon/Data-Products-Course-Project). 
* The application for predicting vehicle fuel economy is hosted on [https://boukhris.shinyapps.io/Data_Products-Course_Project/](https://boukhris.shinyapps.io/Data_Products-Course_Project/).


